Changed SCP monthly
Sirkular/TRB pull request #59
Opened 2021-09-05 01:35 UTC by AurhinDev

Added SCP monthly for G9, Planeshaper & Human Resources

2021-09-16 04:53 UTC, Sirkular requested changes
The strings for the new role names weren't properly added into the globe.roles object in index.js, so this code will not work as expected.

2021-09-22 16:48 UTC, Sirkular requested changes

2021-09-22 16:48 UTC, Sirkular commented on commands.js
> +    values[globe.roles.PLANESHAPER] = 5;
There is still no planeshaper or greater nine string in the global roles object.

2021-09-22 18:27 UTC, AurhinDev reviewed
Roles added

2021-09-22 18:30 UTC, Sirkular approved these changes

2021-09-22 18:30 UTC, merged